### ISSUE TITLE
Regression: Can't scroll on mobile (my bad)

### ISSUE THREAD

**Issue by flesser** [getgrav/grav-theme-antimatter#10]
My commit 543a0cd0c67e2a65bb0c20fc71b853cf5f7d5cb8 seems to completely disable vertical scrolling on (at least some) mobile browsers, which is of course a real show stopper. Sorry for not noticing that earlier.

According to a [StackOverflow answer](https://stackoverflow.com/questions/25164421/) it seems to be the combination of `height: 100%` and Siidebar's `overflow-x: hidden` on html and body. (Which is strange, since overflow-**x** should not interfere with vertical scrolling).

I managed to overcome the issue by adding even more override !important rules (see my [branch](https://github.com/flesser/grav-theme-antimatter/tree/mobile-scroll-fix)), but this neither makes the code more beautiful nor is tested for any other regressions it might cause.

So maybe it would be cleaner for now to just revert 543a0cd0c67e2a65bb0c20fc71b853cf5f7d5cb8 (and 17c9d1a8c7c86ef287cd2ec46dfe066dbba69c4c) until I find another solution to get my 100%-high elements on page.

**Comment by rhukster** [comment]
Just noticed this :)  I've rolled back those changes, and rerelased.
