### ISSUE TITLE
Hidden under header/menu navigation bar

### ISSUE THREAD

**Issue by aptly-io** [getgrav/grav-theme-antimatter#11]
When clicking a bookmark or using the simple search, the anchor is scrolled into view but in the top-left corner of the browser window. Typically hidden under the header/menu-nagivation bar.
Issue on Win7 64bit IE 11.0.17, FF 37.0.1 and Ubuntu 15.04 FF 38.0, Chromium 41.0.2272.76

**Comment by rhukster** [comment]
Can you please provide a screenshot.  I'm not exactly sure what you mean.

**Comment by aptly-io** [comment]
Hello Andy,

Thank you for spending time by looking into it.
I attached a screen cast (vlc can display it).
In the screen cast you see the mouse first hovering a link that will be 
clicked.
Once clicked, the content scrolls until the target.
But the target is hidden under the header/navigation bar.
The mouse is hovering around the hidden content
That does not make sense.
Would be nice if you can do something about it.

PS
This is true for most link targets
(e.g. also when clicking in the TOC "Education" well then that title 
"Education" is covered by navigation bar)

On 2015-06-16 06:55 PM, Andy Miller wrote:
> Can you please provide a screenshot.  I'm not exactly sure what you 
> mean.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/getgrav/grav-theme-antimatter/issues/11#issuecomment-112496361

-- 
Kind regards,
francis

**Comment by rhukster** [comment]
Hmm. is the screencast missing?

**Comment by aptly-io** [comment]
Hello Andy,

According to my "send" box is should be present ... it's about 800k

If it's not working, can you please try this link:
https://aptly.io/grav_hidden_under_header.ogv

(I'll remove it there tomorrow -here it's almost 1AM)


On 2015-06-16 11:59 PM, Andy Miller wrote:
> Hmm. is the screencast missing?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/getgrav/grav-theme-antimatter/issues/11#issuecomment-112580988

-- 
Kind regards,
francis

**Comment by rhukster** [comment]
Oh I see what you mean.  Can you try something for me:

1) use this format when you want an anchor:

```
<a name="test" class="anchor"></a>
```

2) Add this CSS to `css/custom.css`

```
// Anchors
a.anchor {
    display: block;
    position: relative;
    top: -50px;
    visibility: hidden;
}
```

Let me know if that works for you.

**Comment by aptly-io** [comment]
Hello Andy,

Can you have a look? Maybe I did something wrong?
The custom.css is seen by chromium, the element has has the asked for 
class data.
But it's still hidden? For some reason the style seems not associated 
with the anchor I think.

note I can only reply you next morning ...

Kind regards,
francis


https://aptly.io/cv#test


On 2015-06-17 01:05 AM, Andy Miller wrote:
> Oh I see what you mean.  Can you try something for me:
> 
> 1) use this format when you want an anchor:
> 
> ```
> <a name="test" class="anchor"></a>
> ```
> 
> 2) Add this CSS to `css/custom.css`
> 
> ```
> // Anchors
> a.anchor {
>     display: block;
>     position: relative;
>     top: -50px;
>     visibility: hidden;
> }
> ```
> 
> Let me know if that works for you.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/getgrav/grav-theme-antimatter/issues/11#issuecomment-112598841

-- 
Kind regards,
francis

**Comment by rhukster** [comment]
Ok, two things, please remove the `// Anchors` comment, that's for SCSS only and is breaking the CSS

Second thing, if your going to link text like you have you probably want to change the CSS to:

```
a.anchor {
    display: block;
    position: relative;
    margin-top: 50px;
}
```

So as not to hide it

**Comment by aptly-io** [comment]
Hello Andy,

Added my comments inline

On 2015-06-17 01:44 AM, Andy Miller wrote:
> Ok, two things, please remove the `// Anchors` comment, that's for
Okay, did that and now the style is applied on the anchor.
Due to "visibility: hidden;" it is not shown.
When removing this line, the text is still under the navigation bar; 
even overwriten on existing rendered text

> SCSS only and is breaking the CSS
> 
> Second thing, if your going to link text like you have you probably
> want to change the CSS to:
That still stays hidden but it's no longer overwritting other rendered 
information.

> 
> ```
> a.anchor {
>     display: block;
>     position: relative;
>     margin-top: 50px;
> }
> ```
> 
> So as not to hide it
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/getgrav/grav-theme-antimatter/issues/11#issuecomment-112604075

-- 
Kind regards,
francis

**Comment by rhukster** [comment]
Works fine for me in my testing now, not sure what else to say, this is just a CSS thing.
