### ISSUE TITLE
Missing fancy animation in FF and Chromium

### ISSUE THREAD

**Issue by aptly-io** [getgrav/grav-theme-antimatter#12]
I noticed that Win7 64b IE 11.0.17 has this animation that content seems to slide in from left and right sides (both for the navigation bar elements and the main content itself). 
This animation is missing in FF 37.0.1 (on win7 64b) and for the browsers on Ubuntu 15.04 FF 38.0 and Chromium 41.0.2272.76
It would be nice to have as it add some extra touch to once page. And keeping a common look and feel in all browsers seems once of the main points of CSS ...

**Comment by rhukster** [comment]
Are you talking about the off-canvas menu for mobile viewports?

**Comment by aptly-io** [comment]
Hello Andy,

Thanks again for looking into this one.
Please see the differences in animations on the following screen casts:

http://aptly.io/grav_no_anim_ubuntu15.04_64b_chromium.ogv

One IE11 with visible animation:
http://aptly.io/2015-06-17-0024-24.flv


(it's the same web page, different browsers/OS)

On 2015-06-16 06:56 PM, Andy Miller wrote:
> Are you talking about the off-canvas menu for mobile viewports?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/getgrav/grav-theme-antimatter/issues/12#issuecomment-112496547

-- 
Kind regards,
francis

**Comment by rhukster** [comment]
Actually IE has a bug and is showing that animation onload and it's not supposed to!

**Comment by aptly-io** [comment]
Hello Andy,

Will there be a work around for IE?
Or is there something I can do so that all browswers handle it the same?

On 2015-06-17 01:09 AM, Andy Miller wrote:
> Actually IE has a bug and is showing that animation onload and it's
> not supposed to!
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/getgrav/grav-theme-antimatter/issues/12#issuecomment-112599438

-- 
Kind regards,
francis
