### ISSUE TITLE
Bug in Menu Linking

### ISSUE THREAD

**Issue by umbergerba** [getgrav/grav-theme-antimatter#14]
If you download and install Grav; don't change any settings. Then under pages create a new folder called “02.blog”; then upload a file called “blog.md” (wherein the page is also titled “Blog” in the header text); then the clear-cache and refresh the home page so the new page shows in the menu.

Here is where it gets interesting … browse to the new “Blog” page and check the link under the current “GRAV” logo. Clicking on the GRAV logo It is suppose to take you to the root page (home in this case), but instead it wants to take you to the “Blog” page which is your current location.

I've tested this with other pages and it seems to only be a problem when the uploaded page is named “blog.md”.

**Comment by rhukster** [comment]
This has been fixed, just forgot to close this.
