### ISSUE TITLE
Deprecated code

### ISSUE THREAD

**Issue by jeremycherfas** [getgrav/grav-theme-antimatter#140]
I use a child theme of Antimatter, and I am getting this message from my home page, which is modular.

````
  "message" => "Calling "pageLinkName" on template "modular.html.twig" from template "modular.html.twig" is deprecated since version 1.28 and won't be supported anymore in 2.0."
  "file" => "/home/jeremygrav/jeremycherfas.net/user/themes/antimatter/templates/modular.html.twig"
  "line" => 53
````
The page still displays for me on Safari, but others have reported seeing an error. When I look specifically, I see this code in the page source

````
"https://google.com/search?q=RuntimeException+Template+%22modular%2Fshowcase.txt.twig%22+is+not+defined.",
            "https://duckduckgo.com/?q=RuntimeException+Template+%22modular%2Fshowcase.txt.twig%22+is+not+defined.",
            "https://stackoverflow.com/search?q=RuntimeException+Template+%22modular%2Fshowcase.txt.twig%22+is+not+defined."
````

Is Antimatter still being developed as the default theme? I really do not want to have to change themes., but depend on Antimatter not having issues like this.

Thanks

**Comment by rhukster** [comment]
Fixed in the commit above.  BTW, the default theme is now Quark, and that's where all the latest and greatest code will go before it trickles down into other themes.

**Comment by jeremycherfas** [comment]
I will check that commit (and consider moving to Quark, though that will be a lot of work).

Meanwhile, is this related to https://github.com/getgrav/grav/issues/2337#issuecomment-494425351 and would creating my own favicon possibly solve the issue?

**Comment by jeremycherfas** [comment]
I created a favicon and placed it in partials/base.html.twig and that appears to have corrected the problem.
