### ISSUE TITLE
sidebar

### ISSUE THREAD

**Issue by Budy-Love** [getgrav/grav-theme-antimatter#17]
when you scroll a large site and hit the menu button in mobile view you can't see the menu.

.sb-slidebar.sb-static, html.sb-static .sb-slidebar {
    position: absolute
}

position: fixed

solved the problem.

**Comment by rhukster** [comment]
I'm not really able to replicate this.. i can scroll to the very bottom of a long page, hit the mobile menu icon, and the menu displays fine.  Is there anything else?  Perhaps a URL? or a video?
