### ISSUE TITLE
ERR_ICANN_NAME_COLLISION on page 2

### ISSUE THREAD

**Issue by bobrocke** [getgrav/grav-theme-antimatter#18]
I have a fresh Grav blog skeleton install using the default antimatter theme. Clicking on the pagination navigation at the bottom to go to page 2 leads to an error page.

The url for the link is malformed. It's just `page:2` without the baseUrl part.

I just downloaded the skeleton a few minutes ago, so I assume it is completely current.

**Comment by rhukster** [comment]
Sorted in latest releases of Pagination + Antimatter
