### ISSUE TITLE
breadcrumb styling issue

### ISSUE THREAD

**Issue by kat05** [getgrav/grav-theme-antimatter#2]
the last arrow should not be showing, please see pic.
![grav_antimatter_crumbs](https://cloud.githubusercontent.com/assets/5719486/4608039/15cd0fc0-526f-11e4-8080-19d15e1bb4b8.png)

this is not an issue when using the bootstrap theme.

**Comment by rhukster** [comment]
Just a design decision :)

**Comment by namaless** [comment]
If you want remove this you can get my example for editing your breadcrumb template:
<code>
{% set crumbs = breadcrumbs.get() %}

{% if crumbs | length > 1 or config.plugins.breadcrumbs.show_all %}
    {% for crumb in crumbs %}
        {% if not loop | last %}<a class="{{ crumb.slug }} section" href="{{ (crumb.routable) ? crumb.url : '#' }}">{{ crumb.menu }}</a>{% else %}<div class="active section">{{ crumb.menu}}</div>{% endif %}{% if not loop | last %} <i class="right chevron icon divider"></i> {% endif %}
    {% endfor %}
{% endif %}
</code>
