### ISSUE TITLE
Declared language should not be hard coded

### ISSUE THREAD

**Issue by jpfleury** [getgrav/grav-theme-antimatter#22]
The declared language of a page is hard coded to `en`:

    <html lang="en">

See file [`/templates/partials/base.html.twig`](https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/partials/base.html.twig#L2)

However, it should match the actual language. For example, create a page in two languages (say `item.en.md` and `item.fr.md`) and install the plugin *LangSwitcher*. When visiting this page and clicking *Français* in the lang switcher menu, the declared language should be `<html lang="fr">`, not `<html lang="en">`.

**Comment by rhukster** [comment]
Yes, this was done in cacti theme, just haven't gone back and updated the other themes with the same.
