### ISSUE TITLE
Tags work from the right sidebar, but are broken on the document

### ISSUE THREAD

**Issue by mabushey** [getgrav/grav-theme-antimatter#25]
On site: https://www.sendthemtomir.com/

On the right under `Popular Tags` we have `food` that correctly links to `https://www.sendthemtomir.com/tag:food`. The tag for `food` on the left content column incorrectly links to `https://tag:food`

**Comment by rhukster** [comment]
Is your theme up to date? I made several updates to how the sidebar links are built.

**Comment by mabushey** [comment]
* develop 52f6d74 Merge branch 'release/1.7.5' into develop

**Comment by rhukster** [comment]
not sure what your last comment means? you are on 1.7.5 ?

**Comment by mabushey** [comment]
That was the output of `git branch -v`, I'm on commit `52f6d741ae03720687232e7619bcc0799dc39106` from Sept 16. `git pull` says I'm up to date.

**Comment by mabushey** [comment]
This problem can be easily seen at www.sendthemtomir.com

**Comment by Nebucatnetzer** [comment]
I have the same problem. However I'm not yet on the newest theme I need to merge my changes first.
It's rather easy to replicate the bug just click on any tag of a post and it will link to an empty page at least with Chrome.

**Comment by mabushey** [comment]
```
╭─root@sendthemtomir.com /var/www/grav/grav-theme-antimatter  ‹develop›
╰─➤  git branch -v
* develop 3cbbcaf Fixes for blog page form
```

I still have the problem. https://www.sendthemtomir.com is a public site, The tag links from the right column work, but the tags on the left content panel do nothing. If I use "copy link location" in Firefox on the current top article which has a tag of `Debian`, I get "//tag:debian" in my copy buffer.

**Comment by rhukster** [comment]
I think this has been resolved.  Please reopen if not the case.

**Comment by mabushey** [comment]
You are correct. Thank you @rhukster :)

**Comment by Nebucatnetzer** [comment]
Works here as well, thank you for fixing it.
