### ISSUE TITLE
Why the javascript block is not at the end of the page  on base.html.twig ?

### ISSUE THREAD

**Issue by lucawyss** [getgrav/grav-theme-antimatter#27]
Grav and the antimatter theme are very optimized and load fast but there is still render blocking scripts.

Why not moving the {% block javascripts %} in the {% block bottom %} ?

**Comment by rhukster** [comment]
It's not a defacto rule that scripts should be at the bottom.  It's a recommendation but there are downsides.  If you wish to put them at the bottom you can definitely do so.  I've added a named js group at the bottom so anything you assign to that group, will be referenced from the bottom of the the page.
