### ISSUE TITLE
Modular page scroll misplace

### ISSUE THREAD

**Issue by jvesaladesign** [getgrav/grav-theme-antimatter#32]
When viewing modular page the SinglePageNav.js configuration offset selector is #header (user/themes/antimatter/templates/modular.html.twig line 20). This misplaces the scroll cause when page is scrolled the header height changes. Correct placing selector for scrolled header is #header.scrolled?

**Comment by rhukster** [comment]
`#header` should be fine.  `#header.scrolled` is only a more specific version, but `#header` is going to target the same element.
