### ISSUE TITLE
dropdown is not working. 

### ISSUE THREAD

**Issue by Artisy** [getgrav/grav-theme-antimatter#34]
i enabled the dropdown and created a subpage with gravcms.
if i look in the source code i only see the items from the main menu...

**Comment by Artisy** [comment]
hmm. i might have caused the problem myself by changing stylesheets and template a bit.

i will test a new install. to figure that out

**Comment by Artisy** [comment]
nope even with a fres install dropdown is not working.. a fix would be awesome

**Comment by josefstr** [comment]
I can confirm this bug. I did a clean installation, enabled dropdown as explained in https://github.com/getgrav/grav-theme-antimatter, but there is no dropdown menu present.

**Comment by NeonTigerWeb** [comment]
@Artisy can you check if your template YAML file has the following at the top?

`
enabled: true
default_lang: en
dropdown:
  enabled: true
`

**Comment by Artisy** [comment]
I will check it later. But for now i switched to a different template.

Steffen
Op 11 mrt. 2016 00:15 schreef "Rich Starkie" <notifications@github.com>:

**Comment by openscript** [comment]
Still not working.

**Comment by rhukster** [comment]
I have completely rewritten the dropdown style in the develop version of this theme, however that is just the style, and it has always worked.  How do I know? i use it every day :)

You need to have:

1. nested levels of pages.  i.e. a parent page having children, and those children pages can have children of their own.  This is how the dropdown structure is formed.

2. Ensure the pages are 'visible' and 'published' and `non-modular`.  By default pages that have a numeric prefix (eg `01.home`, `02.blog`, etc) are visible (you can override this with `visible: true` in the page header)

3. enable the dropdown option in the yaml.

That's it!

**Comment by SecondeJK** [comment]
The 'visible' yaml markup needs to be a little clearer, I think, as the current documentation doesn't mention this as a prerequisite for the dropdown working.

**Comment by flaviocopes** [comment]
The documentation says 

```
## Visible

visible: false

By default, a page is visible in the navigation if the surrounding folder has a numerical prefix, i.e. /01.home is visible, while /error is not visible. This behavior can be overwritten by setting the visible variable in the header. Valid values are true or false.
```

In other words: a page to be shown in the menu needs to be visible. This is accomplished by either enabling the numeric prefix on the page advanced settings, or by setting it visible (`visible: true` in the yaml or by enabling "Visible" via admin)
