### ISSUE TITLE
Pagination and Taxonomy List Problem?

### ISSUE THREAD

**Issue by oscon** [getgrav/grav-theme-antimatter#36]
Is there a problem with the baseurl for Pagination and the Taxonomy List in theme ANTIMATTER? When the page Blog is used as the homepage, the pagination url seems to be wrong: /grav/page:2 instead of /grav/blog/page:2.
And also the Taxonomy List URL's are wrong: /grav/tag:support instead of /grav/blog/tag:support

**Comment by rhukster** [comment]
When you use `/blog` as the homepage, the `/blog` route is aliased to `/` so this is expected.

**Comment by oscon** [comment]
is there a simple way to fix it, so pagination works with /blog as the homepage?

**Comment by rhukster** [comment]
well pagination should work, just the URLs are pointing to `/` rather than the `/blog`

see: http://demo.getgrav.org/blog-skeleton/

**Comment by oscon** [comment]
@rhukster Sorry! Got it! It was the supported language, which was not set!
