### ISSUE TITLE
Pagination missing?!

### ISSUE THREAD

**Issue by B-iggy** [getgrav/grav-theme-antimatter#42]
Hey guys,

again an obvious issue but pagination does not work for me because... there is no file in partials which can be included?! (pagination.html.twig)
https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/blog.html.twig#L27

**Comment by Vivalldi** [comment]
@B-iggy the antimatter theme does not require pagination. If you install the pagination plugin, then pagination will be an option. https://github.com/getgrav/grav-plugin-pagination

**Comment by B-iggy** [comment]
ahh, thanks. Didn't see that this is a plugin requirement.

**Comment by Vivalldi** [comment]
It's not a requirement. The theme has it included so that if you want pagination you can install. Glad to help. Cheers
