### ISSUE TITLE
"Previous Post" and "Next Post" in the wrong order

### ISSUE THREAD

**Issue by javiruiz** [getgrav/grav-theme-antimatter#5]
Hi,

"Previous Post" and "Next Post" are in wrong order in templates/partials/blog_item.html.twig

I tried to clone the repository and push the changes, but I guess my knowledge of Git is too limited.
I cloned, added the file, commited, but when I tried to push it rejected me.

Thanks,
Javier

**Comment by rhukster** [comment]
I assume you mean **left** shows newer and **right** shows older? I actually implemented this way based on it being the trend in newer themes. Also, it more closely ties in with the order in which pagination works (newer on left, older on the right).  If you wish to change the order, simply invert it your theme.

**Comment by javiruiz** [comment]
That was a fast answer! Yes, that what I meant. I'll change the behaviour in my theme then.

Many thanks for the effort developing this tool!

**Comment by rhukster** [comment]
BTW, if you have not already done so, check this out:

http://getgrav.org/blog/theme-development-with-inheritance

Will make it much easier to change just the bits you need. :)

**Comment by javiruiz** [comment]
I'll do that. Thanks!
