### ISSUE TITLE
Rendering of paragraphs with different sizes

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav-theme-antimatter#58]
Hi guys,
i ran into this issue somehow and I am not sure why.

i write and format articles using MacDown - copy the folder to grav/user and the article is live.

however it seems a random thing that rendering of the articles (most of them anyway) will have the following issue 
- first paragraph font-size is size 16  
- second paragraph font-size is size 18/20 
- all the remaining paragraphs font-size are size 16 

(where the font-size is guestimated)

![captura de ecran din 2016 06 08 la 14 21 21](https://cloud.githubusercontent.com/assets/7076631/15895778/01f12d0e-2d85-11e6-847f-e020e736e78d.png)

Not sure if this has anything to do with the Romanian language being rendered (we have a few different characters glyphs) or is just a setting within the antimatter css somewhere.

**Comment by flaviocopes** [comment]
It's a design "thing" in Grav, unique blog posts. The second paragraph is rendered bigger on purpose with

```
.blog-content-item .list-blog-padding > p:nth-child(2) {
    font-size: 1.2rem;
}
```

I didn't design it, so I'm not sure why this happens, but there must be a reason.

**Comment by JohnMica** [comment]
@flaviocopes thanks for the quick reply. I will dig in the CSS and try to modify some things then :)
