### ISSUE TITLE
rendering of characters 

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav-theme-antimatter#61]
Hi guys, not sure if this is a theme issue of font issue.

It seems that the characters are displayed properly in English/Spanish but not in Romanian. They seem narrower, unbolded weird when rendered both in chrome and safari.
Could this be due to the font used? 
![captura de ecran din 2016 07 01 la 16 34 06](https://cloud.githubusercontent.com/assets/7076631/16526548/aec20e3c-3fa9-11e6-84be-e8d3483ae18b.png)

**Comment by flaviocopes** [comment]
Can you paste the line in text?

**Comment by JohnMica** [comment]
Not sure what line you're referring to Flavio. The picture attached previously?

**Comment by w00fz** [comment]
Yes, he is asking to copy/paste the Romanian text in here so that we can copy it easily and try to replicate the issue, as we have a different keyboard layouts and it's hard for us to reconstruct those characters.

**Comment by JohnMica** [comment]
Utilizarea canabisului de către pacienții cu fibromialgie: efectele asupra eliminării simptomelor și îmbunătățirea calității vieții  This is the text

**Comment by JohnMica** [comment]
Hope you guys can help. Thanks in advance

**Comment by flaviocopes** [comment]
I don't see the issue in Chrome or Firefox but I do see it in Safari, might be a font rendering issue in that browser. You can change the font used by creating a child theme or simply adding a custom css https://github.com/getgrav/grav-plugin-custom-css line that changes the font.

**Comment by JohnMica** [comment]
thanks Flavio, i'll change the font
