### ISSUE TITLE
Font awesome in modular onpage menu

### ISSUE THREAD

**Issue by x1sn0tz** [getgrav/grav-theme-antimatter#73]
I tried to set "icon" parameter for one of modular subpages to display font-awesome icon, but it didn't work.

I tried to hotfix the .../antimatter/templates/modular.html.twig with following code but unsuccessfully

`<li class="{{ current_module }}">
                <a href="#{{ _self.pageLinkName(module.menu) }}">
                    **{% if page.header.icon %}<i class="fa fa-{{ page.header.icon }}"></i>{% endif %}**
                    {{ module.menu }}</a>
  </li>`

May be there is a quick way to make it work?

Thanks

**Comment by flaviocopes** [comment]
`page` refers to the container page (the modular page).

The modular childs are accessible using `module` in that twig, as it's looping through them with `{% for module in page.collection() %}`

**Comment by x1sn0tz** [comment]
Thank for answer. I have a module with header:

---
title: Email
icon: envelope
---

So, as analogy with page, I thought that module header options should be accessible via smth like "module.header.icon", but currently I can't display icon with <i class="fa fa-{{ module.header.icon }}"> in modular.html.twig

**Comment by flaviocopes** [comment]
Try doing a dump() of module.header (https://learn.getgrav.org/advanced/debugging#dump-command-for-twig) and check what's available. Also make sure you clear/disable the page cache.
