### ISSUE TITLE
Broken blog layout on browsers without flexbox support

### ISSUE THREAD

**Issue by flesser** [getgrav/grav-theme-antimatter#8]
I noticed on my smartphone (Nokia N9) that I can't access the right column in http://getgrav.org/blog or the antimatter [blog skeleton site](https://github.com/getgrav/grav-skeleton-blog-site) in general.
The main column takes full screen width as intended, but the sidebar stays outside the right screen edge and doesn't wrap below the main content. To make matters worse, the `viewport`-meta prevents horizontal scrolling, so the contents of the sidebar are inaccessible on many mobile devices.

According to http://www.crossbrowsertool.com/ (just run it on http://getgrav.org/blog), there are still a lot of browsers showing similar behaviour, especially on mobile devices. (And nothing is more frustrating than a "pseudo" _optimized-for-mobile_ webpage were you have to make your smartphone mimic a Desktop browser in order to view all page content)

Digging into the code I found that you rely on the CSS `flex` property to do the responsive layout with Nucleus' `.block` and `.size-*` classes.

The 3rdparty `pure-0.5.0/grids-min.css` is [included only for IE 8+9 as a workaround](https://github.com/getgrav/grav-theme-antimatter/blob/4459893dfc200ef7112b9c65b4085d2ce83e012b/templates/partials/base.html.twig#L20), so the sidebar's `.pure-u-*` do nothing in any other browser (wich got me a little confused during my initial debug attempts).

While looking for a possible solution, I also found that the `.pure-g-r` class (e.g. in [blog.html.twig:30](https://github.com/getgrav/grav-theme-antimatter/blob/4459893dfc200ef7112b9c65b4085d2ce83e012b/templates/blog.html.twig#L30)) is without effect and defined nowhere in the template, even when `grids-min.css` is loaded. (The [Pure Release Notes](https://github.com/yahoo/pure/releases/tag/v0.5.0) say it was deprecated in 0.5.0., scroll down to _"Removing .pure-g-r"_)

A possible solution might be to use `modernizr.js` to check for flexbox support and (transparently, so you don't have to care in the .twig's) decide between Nucleus Grid and Pure Grid?

**Comment by rhukster** [comment]
I'm currently traveling and don't really have access to a browser that doesn't support Flex, but can you test something for me?

if you replace the `.pure-g-r` classes in the twig templates with `.pure-g` and then also remove the browser restrictions on loading the `grids.min.css` so it's loaded for all, it should just work.  Thanks!

**Comment by flesser** [comment]
This kind of works. The sidebar is below the main column now, but the columns keep their 2/3 and 1/3 widths.

**Comment by rhukster** [comment]
Ok, could just be a margin issue at this point. I'll have to look at it more when I get back from vacation and can test with some other browsers. If you come up with a solution that would be great too :)

**Comment by rhukster** [comment]
Should be fixed in latest release. Thanks!
