### ISSUE TITLE
Disable blue filter on header ?

### ISSUE THREAD

**Issue by NK74** [getgrav/grav-theme-antimatter#82]
Hi,

Someone know how to disable blue filter on header image ?

**Comment by flaviocopes** [comment]
The blog page template has a colorize() filter applied to the image: https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/blog.html.twig#L6

You can create a child theme and provide your own blog.html.twig template to override it: https://learn.getgrav.org/themes/customization#theme-inheritance

**Comment by NK74** [comment]
I try to edit/remove 

> .colorize(-35,81,122)

Clear Grav cache and my browser and didn't work

**Comment by NK74** [comment]
Fixed with a custom image on web folder root

**themes\antimatter\templates\modular\showcase.html.twig**

```
{% set showcase_image = page.media.images|first.grayscale().contrast(20).brightness(-125).colorize(-35,81,122) %}
{% if showcase_image %}
	<div class="modular-row showcase flush-top" style="background-image: url({{ showcase_image.url }});">
```

TO
```
{% set showcase_image = page.media.images %}
{% if showcase_image %}
	<div class="modular-row showcase flush-top" style="background-image: url(/kpretc/header.png);">
```
