### ISSUE TITLE
Unreachable code in blog_item.html.twig?

### ISSUE THREAD

**Issue by ulab** [getgrav/grav-theme-antimatter#83]
In blog_item.html.twig you have the following code around lines 53-60:

```
    {% elseif truncate and page.summary != page.content %}
/* ... */
    {% elseif truncate %}
        <div class="p-summary e-content">
            {% if page.summary != page.content %}
                    {{ page.content|truncate(550) }}
```

Will the condition `{% if page.summary != page.content %}` inside the `{% elseif truncate %}` block ever be called if the first elseif already includes the whole condition?

**Comment by flaviocopes** [comment]
You're right, I think it can be safely removed. Do you mind doing a PR?

**Comment by ulab** [comment]
I'll do that, but I have none experience with Grav / Twig whatsoever :). So you'd have to check it closely.
