### ISSUE TITLE
Why is page.content inside blog-header section?

### ISSUE THREAD

**Issue by ScotsScripts** [getgrav/grav-theme-antimatter#84]
In the blog template the page.content item is inside the blog-header section which seems counter-intuitive. Shouldn't the blog content be inside the 2-3 column in the content-wrapper div instead of inside the blog-header div (which should have blog header stuff, right?) 

When a blog post is viewed, the right column with the search form is displayed at the bottom of the blog post, in the content-wrapper div.

Maybe this is by design, but it doesn't make sense to me. I edited the blog.html.twig template and moved the page.content item inside the 2-3 column in the content-wrapper and it looks a lot better.

**Comment by flaviocopes** [comment]
Are you talking about Antimatter? There is no content-wrapper div or blog-header div.

![screen shot 2016-12-11 at 11 30 13](https://cloud.githubusercontent.com/assets/11783388/21079541/368381fa-bf95-11e6-8308-e5c6d7599141.png)

**Comment by ScotsScripts** [comment]
I have the latest version of antimatter and as you can see the blog.html.twig file below, page.content is indeed nested inside the blog-header div. Then a bit further down you see the 2-3 column and the 1-3 column, but the page.content is not included in the 2-3 column as it probably should be.

`{% embed 'partials/base.html.twig' %}
	{% set collection = page.collection() %}

	{% block content %}
		{% set blog_image = page.media.images|first.grayscale().contrast(20).brightness(-100).colorize(-35,81,122) %}

		{% if blog_image %}
		<div class="flush-top blog-header blog-header-image" style="background-image: url({{ blog_image.url }});">
		{% else %}
		<div class="blog-header">
		{% endif %}
			{{ page.content }}
		</div>

			{% if config.plugins.breadcrumbs.enabled %}
				{% include 'partials/breadcrumbs.html.twig' %}
			{% endif %}

		<div class="content-wrapper blog-content-list grid pure-g">
			<div id="listing" class="block pure-u-2-3 h-feed">
				{% for child in collection %}
			        {% include 'partials/blog_item.html.twig' with {'blog':page, 'page':child, 'truncate':true} %}
			    {% endfor %}

                {% if config.plugins.pagination.enabled and collection.params.pagination %}
                    {% include 'partials/pagination.html.twig' with {'base_url':page.url, 'pagination':collection.params.pagination} %}
                {% endif %}
			</div>
			<div id="sidebar" class="block size-1-3 pure-u-1-3">
				{% include 'partials/sidebar.html.twig' with {'blog':page} %}
			</div>
		</div>
	{% endblock %}

{% endembed %}`

**Comment by ScotsScripts** [comment]
Ah, I figured this out- in order to make the blog page look right, it has to be "under" a master blog page. I had some blog page entries in a regular page dropdown. Still getting the hang of Grav and how things are organized.
