### ISSUE TITLE
font awesome 4.7: new icons do not work?!

### ISSUE THREAD

**Issue by qwertologe** [getgrav/grav-theme-antimatter#89]
works:
```
<i class='fa fa-thumbs-o-up'></i>
```

does not work:
```
<i class='fa fa-handshake-o'></i>
<i class='fa fa-handshake'></i>
<i class='fa fa-imdb'></i>
<i class='fa fa-microchip'></i>
<i class='fa fa-grav'></i>
...
```

**Comment by flaviocopes** [comment]
Does not work because latest Antimatter comes with FontAwesome 4.6.3.

**Comment by flaviocopes** [comment]
The current `develop` branch has 4.7, you need to clone / download from GitHub until the next release https://github.com/getgrav/grav-theme-antimatter/commit/6bbf5f2e0d4a099c37733abc4a7ec17f4060c66b

**Comment by qwertologe** [comment]
I thought that i have read the new version in the grav changelog - but anyway. Thanks!

**Comment by flaviocopes** [comment]
I published a release a couple days ago. Should be there now.
