### ISSUE TITLE
Month of blog item displayed in wrong language

### ISSUE THREAD

**Issue by eisenherzz** [getgrav/grav-theme-antimatter#90]
[blog post](https://ak-vielfalt.de/de/archives_month:dec_2016)
My blog Item has English "DEC" instead of "DEZ". Everything else is translated. I do not find the correct point where to set the locale for this.

**Comment by flaviocopes** [comment]
1. Install https://github.com/Perlkonig/grav-plugin-twig-extensions. Make sure you have the PHP `intl` extension installed.
2. In https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/partials/blog_item.html.twig#L12 Change `{{ page.date|date("M") }}` to `{{ page.date|localizeddate('long', 'none', 'it', 'Europe/Rome', 'MMM') }}` (add your language here)

**Comment by flaviocopes** [comment]
Another approach: https://learn.getgrav.org/cookbook/twig-recipes#displaying-a-translated-monthAnother approach: https://learn.getgrav.org/cookbook/twig-recipes#displaying-a-translated-month
