### ISSUE TITLE
Text Widget Example

### ISSUE THREAD

**Issue by Kuurusch** [getgrav/grav-theme-antimatter#93]
Hey, I've set up a Blog and on the right hand side of the blog I have the search plugin and Rss-feed Plugin. But there is also a placeholder "Text Widget Example" with little random text. How can I deactivate this over the admin interface?

**Comment by rhukster** [comment]
It's actually hardcoded in the `templates/partials/sidebar.html.twig` template.  

https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/partials/sidebar.html.twig#L20-L23

Just remove it there.  You can't do it via the admin.  If you plan on making modifications to Antimatter, you should either rename it to your own theme name, or extend it.  see this: https://learn.getgrav.org/themes/customization#theme-inheritance

**Comment by Kuurusch** [comment]
Ah ok, so thats normal? Not a bug? Thanks, yea then I will remove it manually!

**Comment by flaviocopes** [comment]
That should probably be removed from the default sidebar

**Comment by Kuurusch** [comment]
Hey, today I made an update of the theme and wups, the widget was again heare :/ Could you remove it from the template?

**Comment by rhukster** [comment]
We're not going to remove it from the core antimatter theme. 

If you make changes to the antimatter theme, then updating the theme, will of course return the file. 

You should either make a copy of antimatter, and user that theme, or you should use theme inheritance.  https://getgrav.org/blog/theme-development-with-inheritance

**Comment by StefanHolmes** [comment]
I get that newbies should learn, but I adopted Grav because I want to concentrate on site content, not learning how templates work in a CMS. I'm not uninterested, I appreciate Grav as an elegant piece of software, but I'm looking for a user-friendly experience.

What you're describing is user hostile.

**Comment by TomatoCo** [comment]
Grav is remarkably easy to install new themes on. From the user's perspective, have you considered using a third-party theme?

From the developer's perspective, would a compromise be enabling configuration of the sidebar from the pages themselves?

**Comment by slyholborn** [comment]
Hello! configuring the sidebar from the page editor would be great!

**Comment by tanzir71** [comment]
^ Agreed.
