### ISSUE TITLE
configuration setting for width

### ISSUE THREAD

**Issue by qwertologe** [getgrav/grav-theme-antimatter#94]
I consider to migrate to grav but my old (doku)wiki uses a smaller width for the content. So this does not fit very well. It would really help, if i could set the width for the content (desktop mode).

Any chance?

**Comment by flaviocopes** [comment]
Any custom modification can be done using the "Custom CSS" Grav plugin, for example you can start with `body, #header { max-width: 80%; margin: 0 auto; }`
