### ISSUE TITLE
Menu additions don't work on Modular pages

### ISSUE THREAD

**Issue by rsmarples** [getgrav/grav-theme-antimatter#95]
I have a modular page.
Each module gets an entry in the title menu at the top of the page. This is very nice!
Also, the extra static menu's items I have defined locally are also there. This is also very nice!
However, these extra static menu items are NOT clickable :( This is not nice.
See here: <https://roy.marples.name/new_projects/openresolv/config>- the last two top menu items are statically defined in site.yaml

**Comment by flaviocopes** [comment]
There is a 'click' event listener attached to your menu.
I don't have such thing locally, with Antimatter, so I guess it's a customization or a plugin adding it. I cannot find the reference of what's adding that event.

![screen shot 2017-02-25 at 16 25 07](https://cloud.githubusercontent.com/assets/11783388/23332276/380ab70a-fb77-11e6-843e-21f7b542c649.png)

**Comment by rsmarples** [comment]
I disabled all plugins, it still happens :(
To double check, I installed a different theme, and it happens in Afterburner 2 as well.
Maybe a Grav issue itself? Should I log a new ticket in Grav?

**Comment by flaviocopes** [comment]
Ok, I see. Both themes have the problem because they share large parts of the code. The problem occurred when adding links via site.yaml, and on a modular page with `onpage_menu` set. At first, I had another config for my modular page and I didn't get it.

**Comment by flaviocopes** [comment]
Released update. Add an external class property to your links:

```yaml

menu:
  -
    url: https://test.com
    icon: cart-plus
    text: Something
    class: external
```

**Comment by rsmarples** [comment]
Works perfectly thanks!
Unsure why this should be a config option though.

**Comment by flaviocopes** [comment]
It's required by the JavaScript library used to make the on-page menu, used by the theme on modular pages.
